spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    filters: stat,wall,slf4j    # druid监控配置
    max-active: 200
    max-wait: 60000
    initial-size: 5     # 初始化提供的连接数
    min-idle: 5         # 数据库连接池的最小维持连接数
    max-total: 5          # 最大的连接数
    max-wait-millis: 200        # 等待连接获取的最大超时时间
    validation-query: SELECT 1
    use-global-data-source-stat: false
    max-pool-prepared-statement-per-connection-size: 20
    pool-prepared-statements: true
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    min-evictable-idle-time-millis: 60000
    time-between-eviction-runs-millis: 60000
    merge-sql: true
    slow-sql-millis: 500
  profiles:
    active: dev
logging:
  config: classpath:logback-${spring.profiles.active}.xml
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: me.komawei.qiniuloganalyzer.entity
  mapper-locations:
    - classpath:/mappers/**/*.xml
server:
  tomcat:
    accept-count: 200
    min-spare-threads: 10
    max-threads: 200
---
server:
  port: 29999
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.7.121.117:3306/qiniu_log_analyze?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: eekao2o
---
server:
  port: 29999
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.7.121.117:3306/qiniu_log_analyze?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: eekao2o
---
server:
  port: 29999
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://10.7.121.117:3306/qiniu_log_analyze?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: eekao2o